export interface CodeEntry {
  code: string
  cn: string
  en: string
  note?: string
  group?: string  // for U5 grouping by valve type
}

export type BomTier = 'core' | 'structure' | 'material' | 'addon'

export interface CodeTable {
  unit: string      // U1, U2, ...
  dim: string       // D1, D2, ... (standard dimension number)
  name_cn: string
  name_en: string
  sub_cn: string    // short description of BOM impact
  tier: BomTier
  entries: CodeEntry[]
}

export const TIER_CONFIG: Record<BomTier, { label: string; desc: string; color: string }> = {
  core:      { label: '核心层',     desc: '决定BOM的5个维度 — 业务员必须指定，无合理默认值',       color: '#D85A30' },
  structure: { label: '结构层',     desc: '影响BOM形式的6个维度 — 有行业默认值，非常规时需指定',   color: '#1D9E75' },
  material:  { label: '材质细节层', desc: '精确指定零件材质的5个维度 — 通常由核心层自动推导',       color: '#7F77DD' },
  addon:     { label: '附加层',     desc: '不影响BOM物料的3个维度 — 影响工艺/检测/包装',          color: '#888780' },
}

// Metadata per unit: dimension number, short impact description, tier
const UNIT_META: Record<string, { dim: string; sub_cn: string; tier: BomTier }> = {
  U1:  { dim: 'D1',  tier: 'addon',     sub_cn: '低温/抗硫/波纹管等附加特性，不改变BOM物料清单' },
  U2:  { dim: 'D2',  tier: 'core',      sub_cn: '决定零件结构定义完全不同，核心必填' },
  U3:  { dim: 'D3',  tier: 'structure', sub_cn: '小口径默认手轮，大口径默认伞齿轮，影响驱动机构BOM' },
  U4:  { dim: 'D4',  tier: 'structure', sub_cn: '法兰/焊接/螺纹，影响阀体端部结构设计' },
  U5:  { dim: 'D5',  tier: 'structure', sub_cn: '闸板类型(弹性楔/实心楔/平板)，影响流道零件' },
  U6:  { dim: 'D6',  tier: 'core',      sub_cn: '对应件号，直接决定阀座/闸板/阀杆材质' },
  U7:  { dim: 'D7',  tier: 'core',      sub_cn: '决定壁厚、法兰标准、螺柱等级，核心必填' },
  U8:  { dim: 'D8',  tier: 'core',      sub_cn: '决定主体及大部分结构零件材质，核心必填' },
  U9:  { dim: 'D9',  tier: 'core',      sub_cn: '决定尺寸参数、螺柱数量、驱动方式选型' },
  U10: { dim: 'D10', tier: 'structure', sub_cn: 'RF/BW/SW/RTJ 等端面形式，结合连接方式使用' },
  U11: { dim: 'D11', tier: 'structure', sub_cn: '阀盖连接形式，高压(900Lb+)常用压力自密封' },
  U12: { dim: 'D12', tier: 'structure', sub_cn: '全径/缩径，影响阀座尺寸' },
  U13: { dim: 'D13', tier: 'material',  sub_cn: '阀杆材质，默认由主体材质+件号自动推导' },
  U14: { dim: 'D14', tier: 'material',  sub_cn: '阀芯/内件材质，与密封面(U6)高度关联' },
  U15: { dim: 'D15', tier: 'addon',     sub_cn: '仅波纹管阀(U1=W)需要，其余默认A=无波纹管' },
  U16: { dim: 'D16', tier: 'material',  sub_cn: '中法兰垫片，默认缠绕式304+柔性石墨(01)' },
  U17: { dim: 'D17', tier: 'material',  sub_cn: '填料材质，默认柔性石墨，特殊工况指定' },
  U18: { dim: 'D18', tier: 'material',  sub_cn: '螺栓等级，默认由主体材质+压力等级推导' },
  U19: { dim: 'D19', tier: 'addon',     sub_cn: '检测/工艺/包装附加要求，不改变BOM物料' },
}

export const VALVE_CODE_TABLES: CodeTable[] = [
  // ─── U1 特殊功能前缀 ────────────────────────────────────
  {
    unit: 'U1', ...UNIT_META['U1'], name_cn: '特殊功能前缀', name_en: 'Special Function Prefix',
    entries: [
      { code: '(省略)', cn: '无特殊功能', en: 'Standard (omitted)' },
      { code: 'D', cn: '低温型', en: 'Cryogenic / Low-Temperature', note: 'Body: LF2/LCB, extended bonnet' },
      { code: 'B', cn: '保温型', en: 'Jacketed / Heat-Retention', note: 'Steam/heat-tracing jacket' },
      { code: 'H', cn: '缓闭型', en: 'Slow-Closing / Non-Slam', note: 'Dampened closure, anti-waterhammer' },
      { code: 'Q', cn: '快速型', en: 'Quick-Acting' },
      { code: 'K', cn: '抗硫型', en: 'Sour Service (NACE MR0175)', note: 'HIC/SSC resistant, H₂S media' },
      { code: 'W', cn: '波纹管型', en: 'Bellows Seal', note: 'Zero-emission per API 624' },
      { code: 'NK', cn: '真空型', en: 'Vacuum Service' },
    ],
  },

  // ─── U2 阀门类型 ─────────────────────────────────────────
  {
    unit: 'U2', ...UNIT_META['U2'], name_cn: '阀门类型', name_en: 'Valve Type',
    entries: [
      { code: 'Z', cn: '闸阀', en: 'Gate Valve' },
      { code: 'J', cn: '截止阀', en: 'Globe Valve' },
      { code: 'H', cn: '止回阀/底阀', en: 'Check Valve / Foot Valve' },
      { code: 'Q', cn: '球阀', en: 'Ball Valve' },
      { code: 'D', cn: '蝶阀', en: 'Butterfly Valve' },
      { code: 'L', cn: '节流阀', en: 'Throttle Valve' },
      { code: 'U', cn: '柱塞阀', en: 'Piston Valve / Plunger Valve' },
      { code: 'G', cn: '隔膜阀', en: 'Diaphragm Valve' },
      { code: 'A', cn: '安全阀', en: 'Safety / Relief Valve (PSV)' },
      { code: 'X', cn: '旋塞阀', en: 'Plug Valve' },
      { code: 'Y', cn: '减压阀(自力式)', en: 'Self-Actuated Pressure Reducing Valve' },
      { code: 'S', cn: '疏水阀', en: 'Steam Trap' },
      { code: 'N', cn: '针形阀', en: 'Needle Valve' },
      { code: 'PZ', cn: '排渣阀', en: 'Slag Discharge Valve' },
      { code: 'PW', cn: '排污阀', en: 'Blowdown Valve' },
      { code: 'WY', cn: '减压阀(非自力式)', en: 'Externally-Actuated Pressure Reducing Valve' },
      { code: 'GL', cn: 'Y型过滤器', en: 'Y-Strainer' },
    ],
  },

  // ─── U3 驱动方式 ─────────────────────────────────────────
  {
    unit: 'U3', ...UNIT_META['U3'], name_cn: '驱动方式', name_en: 'Actuation Method',
    entries: [
      { code: '(省略)', cn: '手轮/手柄操作', en: 'Handwheel / Lever (manual, omitted)' },
      { code: '0', cn: '电磁动', en: 'Solenoid Operated' },
      { code: '1', cn: '电磁-液动', en: 'Solenoid-Hydraulic' },
      { code: '2', cn: '电-液联动', en: 'Electro-Hydraulic' },
      { code: '3', cn: '蜗轮', en: 'Worm Gear Operated' },
      { code: '4', cn: '正齿轮', en: 'Spur Gear Operated' },
      { code: '5', cn: '伞齿轮', en: 'Bevel Gear Operated' },
      { code: '6', cn: '气动', en: 'Pneumatic Actuated' },
      { code: '7', cn: '液动', en: 'Hydraulic Actuated' },
      { code: '8', cn: '气-液联动', en: 'Pneumatic-Hydraulic' },
      { code: '9', cn: '电动', en: 'Electric Motor Operated (MOV)' },
    ],
  },

  // ─── U4 连接方式 ─────────────────────────────────────────
  {
    unit: 'U4', ...UNIT_META['U4'], name_cn: '连接方式', name_en: 'End Connection Type',
    entries: [
      { code: '1', cn: '内螺纹', en: 'Female Threaded (FT)' },
      { code: '2', cn: '外螺纹', en: 'Male Threaded (MT)' },
      { code: '4', cn: '法兰式', en: 'Flanged' },
      { code: '6', cn: '焊接式', en: 'Welded End' },
      { code: '7', cn: '对夹', en: 'Wafer / Lug Type' },
      { code: '8', cn: '卡箍', en: 'Clamp / Tri-Clamp' },
      { code: '9', cn: '卡套', en: 'Compression Fitting / Ferrule' },
    ],
  },

  // ─── U5 结构形式 ─────────────────────────────────────────
  {
    unit: 'U5', ...UNIT_META['U5'], name_cn: '结构形式', name_en: 'Structure / Trim Design',
    entries: [
      // 闸阀 Gate
      { code: '0', cn: '明杆-楔式单闸板-有弹性槽', en: 'OS&Y, Flexible Wedge', group: '闸阀 Z' },
      { code: '1', cn: '明杆-楔式单闸板-无弹性槽', en: 'OS&Y, Solid Wedge', group: '闸阀 Z' },
      { code: '2', cn: '明杆-楔式双块闸板', en: 'OS&Y, Split Wedge', group: '闸阀 Z' },
      { code: '3', cn: '明杆-平行单块平板', en: 'OS&Y, Single-Disc Parallel Slide (Slab Gate)', group: '闸阀 Z' },
      { code: '4', cn: '明杆-平行双块闸板', en: 'OS&Y, Double-Disc Parallel Slide', group: '闸阀 Z' },
      { code: '5', cn: '暗杆-楔式单块闸板', en: 'NRS, Solid Wedge', group: '闸阀 Z' },
      { code: '6', cn: '暗杆-楔式双块闸板', en: 'NRS, Split Wedge', group: '闸阀 Z' },
      { code: '7', cn: '暗杆-平行双块闸板', en: 'NRS, Double-Disc Parallel Slide', group: '闸阀 Z' },
      // 截止阀/节流阀/针形阀 Globe/Throttle/Needle
      { code: '1', cn: '直通流道-单阀瓣', en: 'Straight Pattern, Single Disc', group: '截止阀/节流阀/针形阀 J/L/N' },
      { code: '2', cn: 'Z型流道', en: 'Z-Pattern (Offset)', group: '截止阀/节流阀/针形阀 J/L/N' },
      { code: '3', cn: '三通流道', en: 'Three-Way Pattern', group: '截止阀/节流阀/针形阀 J/L/N' },
      { code: '4', cn: '角式流道', en: 'Angle Pattern', group: '截止阀/节流阀/针形阀 J/L/N' },
      { code: '5', cn: 'Y形流道', en: 'Y-Pattern (Oblique)', group: '截止阀/节流阀/针形阀 J/L/N' },
      { code: '6', cn: '直通-平衡式阀瓣', en: 'Straight Pattern, Balanced Disc/Plug', group: '截止阀/节流阀/针形阀 J/L/N' },
      { code: '7', cn: '角式-平衡式阀瓣', en: 'Angle Pattern, Balanced Disc/Plug', group: '截止阀/节流阀/针形阀 J/L/N' },
      // 止回阀 Check
      { code: '1', cn: '升降式-直通流道', en: 'Lift Check, Straight Pattern', group: '止回阀 H' },
      { code: '2', cn: '升降式-立式结构', en: 'Lift Check, Vertical (Piston Check)', group: '止回阀 H' },
      { code: '3', cn: '升降式-Z型流道', en: 'Lift Check, Z-Pattern', group: '止回阀 H' },
      { code: '4', cn: '旋启式-单瓣', en: 'Swing Check, Single Disc', group: '止回阀 H' },
      { code: '5', cn: '升降式-Y型/旋启式-多瓣', en: 'Y-Pattern Lift / Multi-Disc Swing', group: '止回阀 H' },
      { code: '6', cn: '旋启式-双瓣', en: 'Dual-Plate / Double-Disc Swing Check', group: '止回阀 H' },
      { code: '7', cn: '蝶形双瓣', en: 'Butterfly (Wafer) Dual-Plate Check', group: '止回阀 H' },
      // 球阀 Ball
      { code: '0', cn: '固定球-半球直通', en: 'Trunnion Mounted, Segmented / Half Ball', group: '球阀 Q' },
      { code: '1', cn: '浮动球-直通', en: 'Floating Ball, Full/Reduced Port', group: '球阀 Q' },
      { code: '2', cn: '浮动球-Y型三通', en: 'Floating Ball, Y-Port 3-Way', group: '球阀 Q' },
      { code: '4', cn: '浮动球-L型三通', en: 'Floating Ball, L-Port 3-Way', group: '球阀 Q' },
      { code: '5', cn: '浮动球-T型三通', en: 'Floating Ball, T-Port 3-Way', group: '球阀 Q' },
      { code: '6', cn: '固定球-四通', en: 'Trunnion Mounted, 4-Way', group: '球阀 Q' },
      { code: '7', cn: '固定球-直通', en: 'Trunnion Mounted, Full/Reduced Port', group: '球阀 Q' },
      { code: '8', cn: '固定球-T型三通', en: 'Trunnion Mounted, T-Port 3-Way', group: '球阀 Q' },
      { code: '9', cn: '固定球-L型三通', en: 'Trunnion Mounted, L-Port 3-Way', group: '球阀 Q' },
      // 蝶阀 Butterfly
      { code: '0', cn: '有密封要求-单偏心', en: 'Tight Shut-off, Single Eccentric', group: '蝶阀 D' },
      { code: '1', cn: '有密封要求-中心垂直板', en: 'Tight Shut-off, Concentric', group: '蝶阀 D' },
      { code: '2', cn: '有密封要求-双偏心', en: 'Tight Shut-off, Double Eccentric', group: '蝶阀 D' },
      { code: '3', cn: '有密封要求-三偏心', en: 'Tight Shut-off, Triple Eccentric', group: '蝶阀 D' },
      { code: '4', cn: '有密封要求-连杆机构', en: 'Tight Shut-off, Link Mechanism', group: '蝶阀 D' },
      { code: '5', cn: '无密封要求-单偏心', en: 'Non-tight, Single Eccentric', group: '蝶阀 D' },
      { code: '6', cn: '无密封要求-中心垂直板', en: 'Non-tight, Concentric', group: '蝶阀 D' },
      { code: '7', cn: '无密封要求-双偏心', en: 'Non-tight, Double Eccentric', group: '蝶阀 D' },
      { code: '8', cn: '无密封要求-三偏心', en: 'Non-tight, Triple Eccentric', group: '蝶阀 D' },
      { code: '9', cn: '无密封要求-连杆机构', en: 'Non-tight, Link Mechanism', group: '蝶阀 D' },
      // 旋塞阀 Plug
      { code: '3', cn: '填料密封-直通', en: 'Packed/Lubricated, Straight', group: '旋塞阀 X' },
      { code: '4', cn: '填料密封-三通T型', en: 'Packed, T-Port 3-Way', group: '旋塞阀 X' },
      { code: '5', cn: '填料密封-四通', en: 'Packed, 4-Way', group: '旋塞阀 X' },
      { code: '7', cn: '油封型-直通', en: 'Oil-Sealed, Straight', group: '旋塞阀 X' },
      { code: '8', cn: '油封型-三通T型', en: 'Oil-Sealed, T-Port 3-Way', group: '旋塞阀 X' },
      // 隔膜阀 Diaphragm
      { code: '1', cn: '屋脊式流道', en: 'Weir Type', group: '隔膜阀 G' },
      { code: '5', cn: '直流式流道', en: 'Straight-Through Type', group: '隔膜阀 G' },
      { code: '6', cn: '直通式流道', en: 'Full-Bore Type', group: '隔膜阀 G' },
      { code: '8', cn: 'Y型角式流道', en: 'Y-Body / Angle Type', group: '隔膜阀 G' },
      // 安全阀 PSV
      { code: '0', cn: '弹簧封闭-带散热片全启式', en: 'Spring-Loaded, Closed Bonnet, Full-Lift', group: '安全阀 A' },
      { code: '1', cn: '弹簧封闭-微启式', en: 'Spring-Loaded, Closed Bonnet, Low-Lift', group: '安全阀 A' },
      { code: '2', cn: '弹簧封闭-全启式/杠杆单杠杆', en: 'Spring-Loaded Closed Full-Lift / Lever', group: '安全阀 A' },
      { code: '4', cn: '弹簧封闭-带扳手全启/杠杆双杠杆', en: 'Spring Full-Lift w/ Lever / Double-Lever', group: '安全阀 A' },
      { code: '6', cn: '先导式全启', en: 'Pilot-Operated Safety Valve, Full-Lift', group: '安全阀 A' },
      { code: '7', cn: '弹簧不封闭-带扳手微启式', en: 'Spring Open Bonnet w/ Lever, Low-Lift', group: '安全阀 A' },
      { code: '8', cn: '弹簧不封闭-带扳手全启式', en: 'Spring Open Bonnet w/ Lever, Full-Lift', group: '安全阀 A' },
      { code: '9', cn: '脉冲式(全冲量)', en: 'Impulse Safety Valve (Full Impulse)', group: '安全阀 A' },
    ],
  },

  // ─── U6 密封面材料 ───────────────────────────────────────
  {
    unit: 'U6', ...UNIT_META['U6'], name_cn: '密封面/衬里材料', name_en: 'Seat / Seal / Lining Material',
    entries: [
      { code: 'B', cn: '锡基合金(巴氏合金)', en: 'Babbitt Metal (Tin-Based)' },
      { code: 'C', cn: '陶瓷(搪瓷衬里)', en: 'Enamel Lined' },
      { code: 'D', cn: '渗氮钢', en: 'Nitrided Steel' },
      { code: 'F', cn: 'PTFE', en: 'PTFE' },
      { code: 'G', cn: '陶瓷', en: 'Ceramic' },
      { code: 'H', cn: '铁基不锈钢(Stellite替代)', en: 'Iron-Based SS (Stellite Alternative)' },
      { code: 'J', cn: '衬胶', en: 'Rubber Lined' },
      { code: 'M', cn: '蒙乃尔合金', en: 'Monel Alloy (Ni-Cu)' },
      { code: 'W', cn: '本体材料(整体)', en: 'Integral / Body Material' },
      { code: 'N', cn: '尼龙塑料', en: 'Nylon' },
      { code: 'P', cn: '渗硼钢', en: 'Boronized Steel' },
      { code: 'Q', cn: '衬铅', en: 'Lead Lined' },
      { code: 'S', cn: '塑料', en: 'Plastic' },
      { code: 'T', cn: '铜合金', en: 'Copper Alloy (Bronze/Brass)' },
      { code: 'X', cn: '橡胶', en: 'Rubber (NBR/EPDM/Viton)' },
      { code: 'Y1', cn: '硬质合金-单堆焊', en: 'Hardfacing Single Layer (Stellite 6)' },
      { code: 'Y2', cn: '硬质合金-双堆焊', en: 'Hardfacing Double Layer (Stellite 6)' },
      { code: 'X/H', cn: '铁基合金镶嵌橡胶', en: 'Iron Alloy Seat + Rubber Insert' },
      { code: 'PFA', cn: '衬PFA', en: 'PFA Lined' },
      { code: 'F1', cn: 'RPTFE', en: 'Reinforced PTFE (Glass-Filled)' },
      { code: 'F2', cn: 'PPL', en: 'PPL (Polyphenylene)' },
      { code: 'F3', cn: 'PEEK', en: 'PEEK' },
      { code: 'F4', cn: '衬PTFE', en: 'PTFE Lined' },
      { code: 'F46', cn: '衬F46', en: 'FEP Lined (F46)' },
    ],
  },

  // ─── U7 压力等级 ─────────────────────────────────────────
  {
    unit: 'U7', ...UNIT_META['U7'], name_cn: '压力等级', name_en: 'Pressure Class',
    entries: [
      // GB/DIN
      { code: '2.5', cn: 'PN2.5', en: 'PN 2.5 (0.25 MPa)', note: 'GB/DIN' },
      { code: '6',   cn: 'PN6',   en: 'PN 6 (0.6 MPa)',    note: 'GB/DIN' },
      { code: '10',  cn: 'PN10',  en: 'PN 10 (1.0 MPa)',   note: 'GB/DIN' },
      { code: '16',  cn: 'PN16',  en: 'PN 16 (1.6 MPa)',   note: 'GB/DIN' },
      { code: '25',  cn: 'PN25',  en: 'PN 25 (2.5 MPa)',   note: 'GB/DIN' },
      { code: '40',  cn: 'PN40',  en: 'PN 40 (4.0 MPa)',   note: 'GB/DIN' },
      { code: '63',  cn: 'PN63',  en: 'PN 63 (6.3 MPa)',   note: 'GB/DIN' },
      { code: '100', cn: 'PN100', en: 'PN 100 (10.0 MPa)', note: 'GB/DIN' },
      { code: '160', cn: 'PN160', en: 'PN 160 (16.0 MPa)', note: 'GB/DIN' },
      { code: '200', cn: 'PN200', en: 'PN 200 (20.0 MPa)', note: 'GB/DIN' },
      { code: '250', cn: 'PN250', en: 'PN 250 (25.0 MPa)', note: 'GB/DIN' },
      { code: '320', cn: 'PN320', en: 'PN 320 (32.0 MPa)', note: 'GB/DIN' },
      { code: '420', cn: 'PN420', en: 'PN 420 (42.0 MPa)', note: 'GB/DIN' },
      { code: '630', cn: 'PN630', en: 'PN 630 (63.0 MPa)', note: 'GB/DIN' },
      { code: '760', cn: 'PN760', en: 'PN 760 (76.0 MPa)', note: 'GB/DIN' },
      // ASME
      { code: '125Lb',  cn: 'CL125',  en: 'Class 125',                         note: 'ASME B16.34' },
      { code: '150Lb',  cn: 'CL150',  en: 'Class 150 (≈PN20)',                  note: 'ASME B16.34' },
      { code: '250Lb',  cn: 'CL250',  en: 'Class 250',                          note: 'ASME B16.34' },
      { code: '300Lb',  cn: 'CL300',  en: 'Class 300 (≈PN50)',                  note: 'ASME B16.34' },
      { code: '600Lb',  cn: 'CL600',  en: 'Class 600 (≈PN100)',                 note: 'ASME B16.34' },
      { code: '800Lb',  cn: 'CL800',  en: 'Class 800 (Forged, ASME B16.11)',    note: 'ASME B16.11' },
      { code: '900Lb',  cn: 'CL900',  en: 'Class 900 (≈PN150)',                 note: 'ASME B16.34' },
      { code: '1500Lb', cn: 'CL1500', en: 'Class 1500 (≈PN250)',                note: 'ASME B16.34' },
      { code: '2500Lb', cn: 'CL2500', en: 'Class 2500 (≈PN420)',                note: 'ASME B16.34' },
      { code: '4500Lb', cn: 'CL4500', en: 'Class 4500 (≈PN720)',                note: 'ASME B16.34' },
      // JIS
      { code: '10K', cn: '10K', en: 'JIS 10K (≈PN16)', note: 'JIS B2220' },
      { code: '20K', cn: '20K', en: 'JIS 20K (≈PN40)', note: 'JIS B2220' },
    ],
  },

  // ─── U8 阀体材料 ─────────────────────────────────────────
  {
    unit: 'U8', ...UNIT_META['U8'], name_cn: '阀体材料', name_en: 'Body / Bonnet Material',
    entries: [
      { code: 'Z',   cn: '灰铸铁',           en: 'Gray Cast Iron (ASTM A126)' },
      { code: 'K',   cn: '可锻铸铁',         en: 'Malleable Cast Iron (ASTM A47)' },
      { code: 'Q',   cn: '球墨铸铁',         en: 'Ductile Iron (ASTM A395/A536)' },
      { code: 'T',   cn: '铜及铜合金',       en: 'Bronze / Brass (ASTM B62/B148)' },
      { code: 'C',   cn: 'A105/WCB 碳钢',    en: 'Carbon Steel Forged A105 / Cast WCB (ASTM A216)' },
      { code: 'C1',  cn: '20#钢',            en: 'Carbon Steel 20# (GB/T 699)' },
      { code: 'C2',  cn: 'LF2/LCB 低温碳钢', en: 'Low-Temp CS Forged LF2 / Cast LCB (ASTM A352)' },
      { code: 'C3',  cn: '35#钢',            en: 'Carbon Steel 35# (GB/T 699)' },
      { code: 'C4',  cn: 'LCC 低温碳钢',     en: 'Low-Temp Carbon Steel LCC (ASTM A352)' },
      { code: 'V',   cn: '15Cr1MoV/12Cr1MoV', en: 'Cr-Mo-V Alloy Steel' },
      { code: 'V1',  cn: '15CrMo',           en: 'Cr-Mo Alloy Steel' },
      { code: 'V2',  cn: '25Cr2Mo1V',        en: 'Cr-Mo-V High-Temp Steel' },
      { code: 'V3',  cn: 'F11/WC6 1¼Cr-½Mo', en: 'Alloy Steel 1¼Cr-½Mo (ASTM A182 F11 / A217 WC6)' },
      { code: 'V4',  cn: 'F22/WC9 2¼Cr-1Mo', en: 'Alloy Steel 2¼Cr-1Mo (ASTM A182 F22 / A217 WC9)' },
      { code: 'P',   cn: '304/CF8 不锈钢',   en: 'SS 304 Forged / CF8 Cast (ASTM A182/A351)' },
      { code: 'P2',  cn: 'F321/CF8C',        en: 'SS 321 / CF8C (ASTM A182/A351)' },
      { code: 'P4',  cn: 'F347',             en: 'SS 347 (ASTM A182)' },
      { code: 'PH',  cn: 'F304H',            en: 'SS 304H (ASTM A182)' },
      { code: 'RH',  cn: 'F316H',            en: 'SS 316H (ASTM A182)' },
      { code: 'P6',  cn: '310/CK20',         en: 'SS 310 / CK20 (ASTM A351)' },
      { code: 'L',   cn: '316L/CF3M',        en: 'SS 316L Forged / CF3M Cast (ASTM A182/A351)' },
      { code: 'L1',  cn: '304L/CF3',         en: 'SS 304L Forged / CF3 Cast (ASTM A182/A351)' },
      { code: 'R',   cn: '316/CF8M',         en: 'SS 316 Forged / CF8M Cast (ASTM A182/A351)' },
      { code: 'R1',  cn: '316Ti',            en: 'SS 316Ti (ASTM A182)' },
      { code: 'R2',  cn: '双相钢2205',       en: 'Duplex SS 2205 / UNS S31803 (ASTM A182 F51)' },
      { code: 'R3',  cn: '双相钢2507',       en: 'Super Duplex SS 2507 / UNS S32750 (ASTM A182 F53)' },
      { code: 'R4',  cn: '904L',             en: 'Super Austenitic 904L / UNS N08904' },
      { code: 'I',   cn: '1Cr5Mo/C5',        en: '5Cr-½Mo (ASTM A217 C5)' },
      { code: 'I1',  cn: 'F5',              en: 'Alloy Steel F5 5Cr-½Mo (ASTM A182)' },
      { code: 'I2',  cn: 'F9',              en: 'Alloy Steel F9 9Cr-1Mo (ASTM A182)' },
      { code: 'I3',  cn: 'F91',             en: 'Alloy Steel F91 9Cr-1Mo-V (ASTM A182)' },
      { code: 'PS1', cn: 'F51/4A 双相钢',   en: 'Duplex 2205 / UNS S31803 (ASTM A182 F51)' },
      { code: 'PS3', cn: 'F53/6A 超双相钢', en: 'Super Duplex 2507 / UNS S32750 (ASTM A182 F53)' },
      { code: 'PS4', cn: 'F55 超双相钢',    en: 'Super Duplex UNS S32760 (ASTM A182 F55)' },
      { code: 'A20', cn: 'ALLOY 20',        en: 'Alloy 20 / Carpenter 20 (UNS N08020)' },
      { code: 'M400', cn: 'NO4400 Monel 400', en: 'Monel 400 (UNS N04400)' },
      { code: 'M500', cn: 'NO5500 Monel K-500', en: 'Monel K-500 (UNS N05500)' },
      { code: 'Ni1', cn: 'Inconel 625',     en: 'Inconel 625 (UNS N06625)' },
      { code: 'Ni2', cn: 'Incoloy 825',     en: 'Incoloy 825 (UNS N08825)' },
      { code: 'HC',  cn: 'Hastelloy C-276', en: 'Hastelloy C-276 (UNS N10276)' },
      { code: 'L1S', cn: 'F304/304L双证钢', en: 'Dual-Certified 304/304L (ASTM A182)' },
      { code: 'LS',  cn: 'F316/316L双证钢', en: 'Dual-Certified 316/316L (ASTM A182)' },
    ],
  },

  // ─── U9 口径 ─────────────────────────────────────────────
  {
    unit: 'U9', ...UNIT_META['U9'], name_cn: '口径', name_en: 'Nominal Size (DN / NPS)',
    entries: [
      { code: '4',    cn: 'DN4',    en: 'NPS 1/8"' },
      { code: '6',    cn: 'DN6',    en: 'NPS 1/4"' },
      { code: '8',    cn: 'DN8',    en: 'NPS 5/16"' },
      { code: '10',   cn: 'DN10',   en: 'NPS 3/8"' },
      { code: '15',   cn: 'DN15',   en: 'NPS 1/2"' },
      { code: '20',   cn: 'DN20',   en: 'NPS 3/4"' },
      { code: '25',   cn: 'DN25',   en: 'NPS 1"' },
      { code: '32',   cn: 'DN32',   en: 'NPS 1-1/4"' },
      { code: '40',   cn: 'DN40',   en: 'NPS 1-1/2"' },
      { code: '50',   cn: 'DN50',   en: 'NPS 2"' },
      { code: '65',   cn: 'DN65',   en: 'NPS 2-1/2"' },
      { code: '80',   cn: 'DN80',   en: 'NPS 3"' },
      { code: '100',  cn: 'DN100',  en: 'NPS 4"' },
      { code: '125',  cn: 'DN125',  en: 'NPS 5"' },
      { code: '150',  cn: 'DN150',  en: 'NPS 6"' },
      { code: '200',  cn: 'DN200',  en: 'NPS 8"' },
      { code: '250',  cn: 'DN250',  en: 'NPS 10"' },
      { code: '300',  cn: 'DN300',  en: 'NPS 12"' },
      { code: '350',  cn: 'DN350',  en: 'NPS 14"' },
      { code: '400',  cn: 'DN400',  en: 'NPS 16"' },
      { code: '450',  cn: 'DN450',  en: 'NPS 18"' },
      { code: '500',  cn: 'DN500',  en: 'NPS 20"' },
      { code: '600',  cn: 'DN600',  en: 'NPS 24"' },
      { code: '700',  cn: 'DN700',  en: 'NPS 28"' },
      { code: '800',  cn: 'DN800',  en: 'NPS 32"' },
      { code: '900',  cn: 'DN900',  en: 'NPS 36"' },
      { code: '1000', cn: 'DN1000', en: 'NPS 40"' },
      { code: '1200', cn: 'DN1200', en: 'NPS 48"' },
      { code: '1400', cn: 'DN1400', en: 'NPS 56"' },
      { code: '1500', cn: 'DN1500', en: 'NPS 60"' },
      { code: '1600', cn: 'DN1600', en: 'NPS 64"' },
      { code: '1800', cn: 'DN1800', en: 'NPS 72"' },
      { code: '2000', cn: 'DN2000', en: 'NPS 80"' },
      { code: '2400', cn: 'DN2400', en: 'NPS 96"' },
    ],
  },

  // ─── U10 两端连接形式 ─────────────────────────────────────
  {
    unit: 'U10', ...UNIT_META['U10'], name_cn: '两端连接形式', name_en: 'End Face / Weld Type',
    entries: [
      { code: 'R', cn: 'RF 突面法兰',    en: 'Raised Face (RF)',         note: 'ASME B16.5' },
      { code: 'F', cn: 'FM 凸凹面',      en: 'Female-Male (FM)',         note: 'ASME B16.5' },
      { code: 'M', cn: 'M 凸面',         en: 'Male Face',                note: 'ASME B16.5' },
      { code: 'T', cn: 'T/LT 榫槽面',   en: 'Tongue & Groove',          note: 'ASME B16.5' },
      { code: 'G', cn: 'G/LG 榫槽面',   en: 'Groove Face',              note: 'ASME B16.5' },
      { code: 'J', cn: 'RJ 环连接面',   en: 'Ring Joint (RTJ)',          note: 'ASME B16.5/API 6A' },
      { code: 'A', cn: 'FF 全平面',      en: 'Flat Face (FF)',           note: 'ASME B16.1' },
      { code: 'S', cn: 'SW 承插焊',      en: 'Socket Weld (SW)',         note: 'ASME B16.11' },
      { code: 'B', cn: 'BW 对焊',        en: 'Butt Weld (BW)',           note: 'ASME B16.25' },
      { code: 'N', cn: '两端带短管',     en: 'Nipple Ends' },
      { code: 'C', cn: 'Rc 管螺纹',      en: 'Female Taper Thread (BSP-T)', note: 'ISO 7/1' },
      { code: 'P', cn: 'NPT 螺纹',       en: 'NPT Thread',               note: 'ASME B1.20.1' },
    ],
  },

  // ─── U11 中法兰连接形式 ───────────────────────────────────
  {
    unit: 'U11', ...UNIT_META['U11'], name_cn: '中法兰连接形式', name_en: 'Bonnet Joint Type',
    entries: [
      { code: '0', cn: '常规配置（省略）', en: 'Standard / Default (omitted)' },
      { code: '1', cn: 'BB螺栓连接阀盖',  en: 'Bolted Bonnet (BB)' },
      { code: '2', cn: 'PSB/PSC压力自密封阀盖', en: 'Pressure Seal Bonnet (PSB/PSC)' },
      { code: '3', cn: 'WB焊接阀盖',      en: 'Welded Bonnet (WB)' },
      { code: '4', cn: 'TB螺纹连接阀盖',  en: 'Threaded/Screwed Bonnet (TB)' },
    ],
  },

  // ─── U12 流道直径 ─────────────────────────────────────────
  {
    unit: 'U12', ...UNIT_META['U12'], name_cn: '流道直径', name_en: 'Bore Type',
    entries: [
      { code: 'A', cn: '常规配置（省略）', en: 'Standard / Default (omitted)' },
      { code: 'B', cn: '标准径',          en: 'Standard Bore / Regular Port' },
      { code: 'Q', cn: '全径',            en: 'Full Bore / Full Port (FB)' },
      { code: 'S', cn: '缩径',            en: 'Reduced Bore / Reduced Port (RB)' },
    ],
  },

  // ─── U13 阀杆材质 ─────────────────────────────────────────
  {
    unit: 'U13', ...UNIT_META['U13'], name_cn: '阀杆材质', name_en: 'Stem Material',
    entries: [
      { code: '00', cn: '常规配置或无阀杆', en: 'Standard / N/A' },
      { code: '01', cn: 'F6a/13Cr',        en: 'ASTM A182 F6a / AISI 410 (UNS S41000)' },
      { code: '02', cn: 'F304',            en: 'ASTM A182 F304 (UNS S30400)' },
      { code: '03', cn: 'F304L',           en: 'ASTM A182 F304L (UNS S30403)' },
      { code: '04', cn: 'F316',            en: 'ASTM A182 F316 (UNS S31600)' },
      { code: '05', cn: 'F316L',           en: 'ASTM A182 F316L (UNS S31603)' },
      { code: '06', cn: '25Cr2Mo1V',       en: 'Cr-Mo-V High-Temp Stem (GB)' },
      { code: '07', cn: 'F321',            en: 'ASTM A182 F321 (UNS S32100)' },
      { code: '08', cn: 'F347',            en: 'ASTM A182 F347 (UNS S34700)' },
      { code: '09', cn: '616HT',           en: 'Alloy 616HT (High-Temp Ni-Based)' },
      { code: '10', cn: '660A/GH2132',     en: 'ASTM A453 Gr.660A / A-286 (UNS S66286)' },
      { code: '11', cn: '17-4PH',          en: 'ASTM A564 Type 630 / 17-4PH (UNS S17400)' },
      { code: '12', cn: 'F11 1¼Cr-½Mo',   en: 'ASTM A182 F11' },
      { code: '13', cn: 'F22 2¼Cr-1Mo',   en: 'ASTM A182 F22' },
      { code: '14', cn: 'F304H',           en: 'ASTM A182 F304H (UNS S30409)' },
      { code: '15', cn: 'F316H',           en: 'ASTM A182 F316H (UNS S31609)' },
      { code: '16', cn: 'F321H',           en: 'ASTM A182 F321H (UNS S32109)' },
      { code: '17', cn: 'F347H',           en: 'ASTM A182 F347H (UNS S34709)' },
      { code: '18', cn: 'F310',            en: 'ASTM A182 F310 (UNS S31000)' },
      { code: '19', cn: 'F316Ti',          en: 'ASTM A182 F316Ti (UNS S31635)' },
      { code: '20', cn: 'ALLOY 20',        en: 'Alloy 20 / Carpenter 20 (UNS N08020)' },
      { code: '21', cn: 'NO4400 Monel 400', en: 'Monel 400 (UNS N04400)' },
      { code: '22', cn: 'NO5500 Monel K-500', en: 'Monel K-500 (UNS N05500)' },
      { code: '23', cn: 'Inconel 625',     en: 'Inconel 625 (UNS N06625)' },
      { code: '24', cn: 'Incoloy 825',     en: 'Incoloy 825 (UNS N08825)' },
      { code: '25', cn: '双相钢2205/F51',  en: 'Duplex 2205 / F51 (UNS S31803)' },
      { code: '26', cn: '双相钢2507',      en: 'Super Duplex 2507 (UNS S32750)' },
      { code: '27', cn: '904L',            en: 'Super Austenitic 904L (UNS N08904)' },
      { code: '28', cn: 'HC-276',          en: 'Hastelloy C-276 (UNS N10276)' },
      { code: '29', cn: 'FXM-19',          en: 'Nitronic 50 / XM-19 (UNS S20910)' },
    ],
  },

  // ─── U14 阀芯材质 ─────────────────────────────────────────
  {
    unit: 'U14', ...UNIT_META['U14'], name_cn: '阀芯/内件材质', name_en: 'Trim Material (Seat/Disc/Ball)',
    entries: [
      { code: '00', cn: '常规配置',        en: 'Standard / Default' },
      { code: '01', cn: '13Cr/A105/WCB',  en: '13Cr Martensitic SS or Carbon Steel Trim' },
      { code: '02', cn: 'LF2/LCB',        en: 'Low-Temp Carbon Steel (ASTM A350 LF2/A352 LCB)' },
      { code: '03', cn: '304/CF8',         en: 'SS 304 / CF8 (ASTM A182/A351)' },
      { code: '04', cn: '316/CF8M',        en: 'SS 316 / CF8M (ASTM A182/A351)' },
      { code: '05', cn: '304L/CF3',        en: 'SS 304L / CF3 (ASTM A182/A351)' },
      { code: '06', cn: '316L/CF3M',       en: 'SS 316L / CF3M (ASTM A182/A351)' },
      { code: '07', cn: 'F321/CF8C',       en: 'SS 321 / CF8C (ASTM A182/A351)' },
      { code: '08', cn: 'F347',            en: 'SS 347 (ASTM A182 F347)' },
      { code: '09', cn: '616HT',           en: 'Alloy 616HT (High-Temp Ni-Based)' },
      { code: '10', cn: '660A/GH2132',     en: 'A-286 / Gr.660A (UNS S66286)' },
      { code: '11', cn: '17-4PH',          en: '17-4PH / Type 630 (UNS S17400)' },
      { code: '12', cn: 'F11/WC6 1¼Cr-½Mo', en: 'ASTM A182 F11 / A217 WC6' },
      { code: '13', cn: 'F22/WC9 2¼Cr-1Mo', en: 'ASTM A182 F22 / A217 WC9' },
      { code: '14', cn: 'F304H',           en: 'SS 304H (UNS S30409)' },
      { code: '15', cn: 'F316H',           en: 'SS 316H (UNS S31609)' },
      { code: '16', cn: 'F321H',           en: 'SS 321H (UNS S32109)' },
      { code: '17', cn: 'F347H',           en: 'SS 347H (UNS S34709)' },
      { code: '18', cn: 'F310/CK20',       en: 'SS 310 / CK20 (UNS S31000)' },
      { code: '19', cn: 'F316Ti',          en: 'SS 316Ti (UNS S31635)' },
      { code: '20', cn: 'ALLOY 20',        en: 'Alloy 20 (UNS N08020)' },
      { code: '21', cn: 'NO4400 Monel 400', en: 'Monel 400 (UNS N04400)' },
      { code: '22', cn: 'NO5500 Monel K-500', en: 'Monel K-500 (UNS N05500)' },
      { code: '23', cn: 'Inconel 625',     en: 'Inconel 625 (UNS N06625)' },
      { code: '24', cn: 'Incoloy 825',     en: 'Incoloy 825 (UNS N08825)' },
      { code: '25', cn: '双相钢2205/F51',  en: 'Duplex 2205 / F51 / 4A (UNS S31803)' },
      { code: '26', cn: '双相钢2507',      en: 'Super Duplex 2507 (UNS S32750)' },
      { code: '27', cn: '904L',            en: '904L (UNS N08904)' },
      { code: '28', cn: 'HC-276',          en: 'Hastelloy C-276 (UNS N10276)' },
      { code: '29', cn: 'FXM-19',          en: 'Nitronic 50 / XM-19 (UNS S20910)' },
      { code: '30', cn: '1Cr5Mo/C5',       en: '5Cr-0.5Mo (ASTM A217 C5)' },
      { code: '31', cn: 'F5',              en: 'ASTM A182 F5, 5Cr-0.5Mo' },
      { code: '32', cn: 'F9',              en: 'ASTM A182 F9, 9Cr-1Mo' },
      { code: '33', cn: 'F91',             en: 'ASTM A182 F91, 9Cr-1Mo-V' },
      { code: '34', cn: 'F53/6A 超双相钢', en: 'Super Duplex F53 / 6A (UNS S32750)' },
      { code: '35', cn: 'F55 超双相钢',    en: 'Super Duplex F55 (UNS S32760)' },
    ],
  },

  // ─── U15 波纹管材质 ───────────────────────────────────────
  {
    unit: 'U15', ...UNIT_META['U15'], name_cn: '波纹管材质', name_en: 'Bellows Material',
    entries: [
      { code: 'A', cn: '常规（无波纹管）',      en: 'N/A (No Bellows)' },
      { code: 'B', cn: '国产波纹管 304',         en: 'Domestic Bellows, SS 304' },
      { code: 'C', cn: '国产波纹管 316',         en: 'Domestic Bellows, SS 316' },
      { code: 'D', cn: '国产波纹管 316L',        en: 'Domestic Bellows, SS 316L' },
      { code: 'E', cn: '国产波纹管 321',         en: 'Domestic Bellows, SS 321' },
      { code: 'F', cn: '国产波纹管 316Ti',       en: 'Domestic Bellows, SS 316Ti' },
      { code: 'G', cn: '国产波纹管 Inconel 625', en: 'Domestic Bellows, Inconel 625' },
      { code: 'H', cn: '国产波纹管 HC-276',      en: 'Domestic Bellows, Hastelloy C-276' },
      { code: 'I', cn: '进口波纹管 316L',        en: 'Imported Bellows, SS 316L' },
      { code: 'J', cn: '进口波纹管 321',         en: 'Imported Bellows, SS 321' },
      { code: 'K', cn: '进口波纹管 316Ti',       en: 'Imported Bellows, SS 316Ti' },
      { code: 'L', cn: '进口波纹管 Inconel 625', en: 'Imported Bellows, Inconel 625' },
      { code: 'M', cn: '进口波纹管 HC-276',      en: 'Imported Bellows, Hastelloy C-276' },
    ],
  },

  // ─── U16 垫片材质 ─────────────────────────────────────────
  {
    unit: 'U16', ...UNIT_META['U16'], name_cn: '垫片材质', name_en: 'Gasket Material',
    entries: [
      { code: '00', cn: '常规配置', en: 'Standard / Default' },
      // 缠绕式垫片 SWG
      { code: '01', cn: '缠绕式垫片 304+柔性石墨', en: 'SWG, SS 304 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '02', cn: '缠绕式垫片 304L+柔性石墨', en: 'SWG, SS 304L + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '03', cn: '缠绕式垫片 316+柔性石墨', en: 'SWG, SS 316 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '04', cn: '缠绕式垫片 316L+柔性石墨', en: 'SWG, SS 316L + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '05', cn: '缠绕式垫片 321+柔性石墨', en: 'SWG, SS 321 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '06', cn: '缠绕式垫片 347+柔性石墨', en: 'SWG, SS 347 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '07', cn: '缠绕式垫片 Monel+柔性石墨', en: 'SWG, Monel + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '08', cn: '缠绕式垫片 镍基合金+柔性石墨', en: 'SWG, Ni-Alloy + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '09', cn: '缠绕式垫片 Alloy 20+柔性石墨', en: 'SWG, Alloy 20 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '10', cn: '缠绕式垫片 HC4+柔性石墨', en: 'SWG, Hastelloy C4 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '11', cn: '缠绕式垫片 317+柔性石墨', en: 'SWG, SS 317 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '12', cn: '缠绕式垫片 31803+柔性石墨', en: 'SWG, Duplex 2205 + Flexible Graphite', group: '缠绕式垫片 SWG' },
      { code: '13', cn: '缠绕式垫片 镍基合金+ThermaPur', en: 'SWG, Ni-Alloy + ThermaPur', group: '缠绕式垫片 SWG' },
      // 复合式垫片 Kammprofile
      { code: '14', cn: '复合式垫片 304+柔性石墨', en: 'Kammprofile, SS 304 + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '15', cn: '复合式垫片 304L+柔性石墨', en: 'Kammprofile, SS 304L + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '16', cn: '复合式垫片 316+柔性石墨', en: 'Kammprofile, SS 316 + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '17', cn: '复合式垫片 316L+柔性石墨', en: 'Kammprofile, SS 316L + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '18', cn: '复合式垫片 321+柔性石墨', en: 'Kammprofile, SS 321 + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '19', cn: '复合式垫片 347+柔性石墨', en: 'Kammprofile, SS 347 + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '20', cn: '复合式垫片 Monel+柔性石墨', en: 'Kammprofile, Monel + Flexible Graphite', group: '复合式垫片 Kammprofile' },
      { code: '21', cn: '复合式垫片 镍基合金', en: 'Kammprofile, Ni-Alloy', group: '复合式垫片 Kammprofile' },
      { code: '22', cn: '复合式垫片 Alloy 20', en: 'Kammprofile, Alloy 20', group: '复合式垫片 Kammprofile' },
      { code: '23', cn: '复合式垫片 HC4', en: 'Kammprofile, Hastelloy C4', group: '复合式垫片 Kammprofile' },
      { code: '24', cn: '复合式垫片 317', en: 'Kammprofile, SS 317', group: '复合式垫片 Kammprofile' },
      { code: '25', cn: '复合式垫片 31803双相钢', en: 'Kammprofile, Duplex 2205', group: '复合式垫片 Kammprofile' },
      // 非金属垫片
      { code: '26', cn: '垫片 PTFE', en: 'PTFE Sheet Gasket', group: '非金属垫片' },
      { code: '27', cn: '垫片 RPTFE', en: 'Reinforced PTFE Sheet Gasket', group: '非金属垫片' },
      { code: '28', cn: '垫片 PPL', en: 'PPL Sheet Gasket', group: '非金属垫片' },
      { code: '29', cn: '垫片 PEEK', en: 'PEEK Sheet Gasket', group: '非金属垫片' },
      { code: '30', cn: '垫片 PCTFE', en: 'PCTFE (Kel-F) Sheet Gasket', group: '非金属垫片' },
      { code: '31', cn: '垫片 芳纶纤维', en: 'Aramid Fiber (Kevlar) Sheet Gasket', group: '非金属垫片' },
      // 包覆垫片
      { code: '32', cn: '包覆垫片 304+PTFE', en: 'Metal-Jacketed 304 + PTFE', group: '包覆垫片' },
      { code: '33', cn: '包覆垫片 304+RPTFE', en: 'Metal-Jacketed 304 + RPTFE', group: '包覆垫片' },
      { code: '34', cn: '包覆垫片 304L+PTFE', en: 'Metal-Jacketed 304L + PTFE', group: '包覆垫片' },
      { code: '35', cn: '包覆垫片 304L+RPTFE', en: 'Metal-Jacketed 304L + RPTFE', group: '包覆垫片' },
      { code: '36', cn: '包覆垫片 316+PTFE', en: 'Metal-Jacketed 316 + PTFE', group: '包覆垫片' },
      { code: '37', cn: '包覆垫片 316+RPTFE', en: 'Metal-Jacketed 316 + RPTFE', group: '包覆垫片' },
      { code: '38', cn: '包覆垫片 316L+PTFE', en: 'Metal-Jacketed 316L + PTFE', group: '包覆垫片' },
      { code: '39', cn: '包覆垫片 316L+RPTFE', en: 'Metal-Jacketed 316L + RPTFE', group: '包覆垫片' },
      { code: '40', cn: '包覆垫片 321+PTFE', en: 'Metal-Jacketed 321 + PTFE', group: '包覆垫片' },
      { code: '41', cn: '包覆垫片 321+RPTFE', en: 'Metal-Jacketed 321 + RPTFE', group: '包覆垫片' },
      { code: '42', cn: '包覆垫片 Monel+PTFE', en: 'Metal-Jacketed Monel + PTFE', group: '包覆垫片' },
      { code: '43', cn: '包覆垫片 Monel+RPTFE', en: 'Metal-Jacketed Monel + RPTFE', group: '包覆垫片' },
      { code: '44', cn: '包覆垫片 Monel+PFA', en: 'Metal-Jacketed Monel + PFA', group: '包覆垫片' },
      { code: '45', cn: '包覆垫片 Alloy 20+PTFE', en: 'Metal-Jacketed Alloy 20 + PTFE', group: '包覆垫片' },
      { code: '46', cn: '包覆垫片 Alloy 20+RPTFE', en: 'Metal-Jacketed Alloy 20 + RPTFE', group: '包覆垫片' },
      { code: '47', cn: '包覆垫片 镍基合金+PTFE', en: 'Metal-Jacketed Ni-Alloy + PTFE', group: '包覆垫片' },
      { code: '48', cn: '包覆垫片 镍基合金+RPTFE', en: 'Metal-Jacketed Ni-Alloy + RPTFE', group: '包覆垫片' },
      // 波齿垫片 CMG
      { code: '49', cn: '波齿垫软铁', en: 'Corrugated Metal Gasket (CMG), Soft Iron', group: '波齿垫片 CMG' },
      { code: '50', cn: '波齿垫 304', en: 'CMG, SS 304', group: '波齿垫片 CMG' },
      { code: '51', cn: '波齿垫 304L', en: 'CMG, SS 304L', group: '波齿垫片 CMG' },
      { code: '52', cn: '波齿垫 316', en: 'CMG, SS 316', group: '波齿垫片 CMG' },
      { code: '53', cn: '波齿垫 316L', en: 'CMG, SS 316L', group: '波齿垫片 CMG' },
      { code: '54', cn: '波齿垫 12Cr5Mo', en: 'CMG, 5Cr-Mo Alloy', group: '波齿垫片 CMG' },
      // 环形垫 RTJ
      { code: '55', cn: '八角垫软铁', en: 'Ring Joint Gasket (RTJ) Octagonal, Soft Iron', group: '环形垫 RTJ' },
      { code: '56', cn: '八角垫 10#钢', en: 'RTJ Octagonal, 10# Carbon Steel', group: '环形垫 RTJ' },
      { code: '57', cn: '八角垫 304', en: 'RTJ Octagonal, SS 304', group: '环形垫 RTJ' },
      { code: '58', cn: '八角垫 304L', en: 'RTJ Octagonal, SS 304L', group: '环形垫 RTJ' },
      { code: '59', cn: '八角垫 316', en: 'RTJ Octagonal, SS 316', group: '环形垫 RTJ' },
      { code: '60', cn: '八角垫 316L', en: 'RTJ Octagonal, SS 316L', group: '环形垫 RTJ' },
      { code: '61', cn: '八角垫 1Cr5Mo', en: 'RTJ Octagonal, 5Cr-Mo Alloy', group: '环形垫 RTJ' },
    ],
  },

  // ─── U17 填料材质 ─────────────────────────────────────────
  {
    unit: 'U17', ...UNIT_META['U17'], name_cn: '填料材质', name_en: 'Packing Material',
    entries: [
      { code: 'A', cn: '常规配置',            en: 'Standard / Default' },
      { code: 'B', cn: '柔性石墨',            en: 'Flexible Graphite (Die-Formed Rings)' },
      { code: 'C', cn: 'PTFE',               en: 'PTFE (Virgin)' },
      { code: 'D', cn: 'RPTFE',              en: 'Reinforced PTFE (Glass-Filled)' },
      { code: 'E', cn: 'PPL',                en: 'PPL (Polyphenylene)' },
      { code: 'F', cn: 'PCTFE',              en: 'PCTFE (Kel-F)' },
      { code: 'G', cn: '低泄漏填料石墨',      en: 'Low-Emission Graphite Packing (API 622/TA-Luft)' },
      { code: 'H', cn: '低泄漏填料PTFE',      en: 'Low-Emission PTFE Packing' },
      { code: 'I', cn: '低泄漏填料RPTFE',     en: 'Low-Emission RPTFE Packing' },
      { code: 'J', cn: '碳纤维填料',          en: 'Carbon Fiber Packing' },
      { code: 'K', cn: '热媒专用填料',        en: 'Heat Transfer Fluid (HTF) Service Packing' },
      { code: 'L', cn: '耐高温填料',          en: 'High-Temperature Packing' },
      { code: 'M', cn: '高温固力特填料',      en: 'High-Temp Consolidated Graphite Packing' },
      { code: 'N', cn: '芳纶纤维',            en: 'Aramid Fiber (Kevlar) Packing' },
      { code: 'O', cn: '无油柔性石墨',        en: 'Oil-Free Flexible Graphite Packing' },
    ],
  },

  // ─── U18 螺栓材质 ─────────────────────────────────────────
  {
    unit: 'U18', ...UNIT_META['U18'], name_cn: '螺栓材质', name_en: 'Bolting Material',
    entries: [
      { code: '00', cn: '常规配置',          en: 'Standard / Default' },
      { code: '01', cn: 'B7',               en: 'ASTM A193 B7 (4140/4142 Q&T)',        note: '通用高温 ≤450°C' },
      { code: '02', cn: 'B7M',              en: 'ASTM A193 B7M (HRC≤22)',              note: '抗硫 NACE MR0175' },
      { code: '03', cn: 'B8 (304 SS)',      en: 'ASTM A193 B8, Solution Annealed',     note: '耐腐蚀/低温' },
      { code: '04', cn: 'B8-2 (304 SS)',    en: 'ASTM A193 B8 Class 2, Strain Hardened', note: '高强度耐腐蚀' },
      { code: '05', cn: 'B8M (316 SS)',     en: 'ASTM A193 B8M, Solution Annealed',    note: '耐腐蚀/海洋' },
      { code: '06', cn: 'B8M-2 (316 SS)',  en: 'ASTM A193 B8M Class 2, Strain Hardened', note: '高强度海洋' },
      { code: '07', cn: 'L7',               en: 'ASTM A320 L7 (4140/4142 Q&T)',        note: '低温 ≤-101°C' },
      { code: '08', cn: 'L7M',              en: 'ASTM A320 L7M (HRC≤22)',              note: '低温抗硫' },
      { code: '09', cn: 'B16',              en: 'ASTM A193 B16 (Cr-Mo-V)',             note: '高温 ≤538°C' },
      { code: '10', cn: 'B16镀锌',         en: 'ASTM A193 B16, Zinc-Plated' },
      { code: '11', cn: 'B16镀镍',         en: 'ASTM A193 B16, Nickel-Plated' },
      { code: '12', cn: '660A/GH2132',      en: 'ASTM A453 Gr.660A / A-286 (UNS S66286)', note: '超高温 ≤700°C' },
      { code: '13', cn: 'B8T (321 SS)',     en: 'ASTM A193 B8T (321 SS)',              note: '高温耐腐蚀' },
      { code: '14', cn: '35CrMoA',          en: '35CrMoA (GB/T 3077)',                 note: '国标通用' },
      { code: '15', cn: '40Cr',             en: '40Cr (GB/T 3077)',                    note: '国标通用' },
      { code: '16', cn: '25Cr2Mo1V',        en: '25Cr2Mo1V (GB/T 12228)',              note: '国标超高温' },
      { code: '17', cn: 'B348 Gr.2 钛',    en: 'ASTM B348 Gr.2 Titanium (UNS R50400)', note: '强腐蚀/轻量化' },
    ],
  },

  // ─── U19 特殊要求 ─────────────────────────────────────────
  {
    unit: 'U19', ...UNIT_META['U19'], name_cn: '特殊要求', name_en: 'Special Requirements',
    entries: [
      { code: '00', cn: '无特殊要求',         en: 'No Special Requirements' },
      { code: '01', cn: '阀门配件（配对法兰、螺栓、垫片等）', en: 'Loose Accessories (Mating Flanges, Bolts, Gaskets)' },
      { code: '02', cn: '设计标准按GB/T 12224或ASME B16.34', en: 'Design per GB/T 12224 or ASME B16.34' },
      { code: '03', cn: '介质氢气',           en: 'Hydrogen Service (per API 6DSS / Nelson Curve)' },
      { code: '04', cn: '介质氧气',           en: 'Oxygen Service (Cleaned for O₂, per CGA G-4.4)' },
      { code: '05', cn: '低硫磷',             en: 'Low S&P (S≤0.020%, P≤0.020%)' },
      { code: '06', cn: '加长阀盖（按-46°C要求加长的）', en: 'Extended Bonnet per -46°C (per ASME B16.34)' },
      { code: '07', cn: '加长阀盖（按-196°C要求加长）', en: 'Extended Bonnet per -196°C (Cryogenic/LNG)' },
      { code: '08', cn: '加长阀盖（其余有特殊要求加长的）', en: 'Extended Bonnet (Other Special Requirement)' },
      { code: '09', cn: '需BA级抛光',         en: 'BA (Bright Annealed) Surface Finish Required' },
      { code: '10', cn: '需EP级抛光',         en: 'EP (Electropolished) Surface Finish Required' },
      { code: '11', cn: '脱油脱脂要求',       en: 'Degreased / Cleaned (per CGA G-4.1 or ASTM G93)' },
      { code: '12', cn: '坡口射线检测(抽检100%)', en: 'Weld Bevel RT 100%' },
      { code: '13', cn: '关键部位射线检测(抽检100%)', en: 'Critical Zone RT 100%' },
      { code: '14', cn: '阀门整体100%射线检测', en: 'Full Valve Body RT 100%' },
      { code: '15', cn: '坡口射线检测(抽检50%)', en: 'Weld Bevel RT 50% Spot' },
      { code: '16', cn: '关键部位射线检测(抽检50%)', en: 'Critical Zone RT 50% Spot' },
      { code: '17', cn: '阀门整体射线检测(抽检50%)', en: 'Full Valve Body RT 50% Spot' },
      { code: '18', cn: '坡口射线检测(抽检20%~50%)', en: 'Weld Bevel RT 20%-50% Spot' },
      { code: '19', cn: '关键部位射线检测(抽检20%~50%)', en: 'Critical Zone RT 20%-50% Spot' },
      { code: '20', cn: '阀门整体射线检测(抽检20%~50%)', en: 'Full Valve Body RT 20%-50% Spot' },
      { code: '21', cn: '坡口射线检测(抽检20%及以下)', en: 'Weld Bevel RT ≤20% Spot' },
      { code: '22', cn: '关键部位射线检测(抽检20%及以下)', en: 'Critical Zone RT ≤20% Spot' },
      { code: '23', cn: '阀门整体射线检测(抽检20%及以下)', en: 'Full Valve Body RT ≤20% Spot' },
      { code: '24', cn: '防火要求',           en: 'Fire-Safe / Fire-Tested (per API 607 / BS 6755-2)' },
      { code: '25', cn: '阀门阀座弹簧材质Inconel X-750', en: 'Seat Spring: Inconel X-750 (UNS N07750)' },
      { code: '26', cn: '整体锻',             en: 'Forged Body (Integral Forging)' },
      { code: '27', cn: '组合件',             en: 'Assembly / Multi-Component Construction' },
      { code: '28', cn: '泄压孔',             en: 'Body Cavity Relief / Vent Hole (DBB)' },
      { code: '29', cn: '夹套进出口尺寸:DN20 PN16', en: 'Jacket Inlet/Outlet: DN20 PN16' },
      { code: '30', cn: '阀芯乙烯涂层',       en: 'Trim Ethylene (Nylon 11 / Rilsan) Coating' },
      { code: '31', cn: '禁铜及铜合金',       en: 'No Copper / Copper-Alloy Components (Cu-Free)' },
      { code: '32', cn: 'API 623',            en: 'Per API 623 (Steel Gate Valves, Flanged & BW)' },
    ],
  },
]
